# 4. 데이터 분석 연습문제 4

### 인구 현황 데이터 분석
* data/인구현황.csv 를 사용하세요.

In [5]:
import pandas as pd

data = pd.read_csv('../인구현황.csv')

In [55]:
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns

In [ ]:
# 폰트이름과 폰트파일 정보 출력 list comprehension 
[ (font.name, font.fname) for font in fm.fontManager.ttflist if 'Mal' in font.name ]

In [ ]:
# font name을 알고 있다면 생략가능
# 한글폰트 path 설정
font_path = 'C:\\Windows\\Fonts\\malgun.ttf'
# font의 파일 정보로 font name을 알아내기
font_name = fm.FontProperties(fname=font_path).get_name()
print(font_name)

In [58]:
# matplotlib의 rc(run command) 함수를 사용해서 font name(Malgun Gothic) 설정
matplotlib.rc('font', family=font_name)

##### 1. 지역별 총 인구수 Top 5

In [ ]:
p_data = data[data['행정기관'] != '전국'].copy()
p_data.head()

In [88]:
data.columns

Index(['행정기관코드', '행정기관', '총인구수', '세대수', '세대당 인구', '남자 인구수', '여자 인구수', '남여 비율'], dtype='object')

In [89]:
p_data[['행정기관', '총인구수']].sort_values(by='총인구수', ascending=False).head(5)

     행정기관      총인구수
9     경기도  13694685
1   서울특별시   9331828
2   부산광역시   3266598
16   경상남도   3228380
4   인천광역시   3021010

##### 1-1. 지역별 총 인구수 plot

In [ ]:
g_df = p_data.loc[p_data['행정기관'] != '전국'].copy()
pop_order = g_df.sort_values('총인구수',ascending=False)['행정기관']

# subplots() 함수를 사용하여 axes 객체를 생성하기
figure, axes1 = plt.subplots(nrows=1,ncols=1)
figure.set_size_inches(18,12)

# seaborn의 barplot() 함수 호출하기 - 행정기관과 총인구수
sns.barplot(data=g_df, x="행정기관", y="총인구수", ax=axes1, hue="행정기관", order=pop_order)

axes1.set_title(f'지역별 총인구수')
axes1.set_xticklabels(axes1.get_xticklabels(), rotation=45, horizontalalignment='right', fontsize=12)

plt.show()

##### 2. 세대당 인구수 높은 지역 Top 5

In [91]:
p_data[['행정기관', '세대당 인구']].sort_values(by='세대당 인구', ascending=False).head(5).reset_index(drop=True)

      행정기관  세대당 인구
0  세종특별자치시    2.39
1      경기도    2.26
2    울산광역시    2.22
3    인천광역시    2.20
4    대구광역시    2.14

##### 2-1. 지역별 세대당 인구 plot

In [ ]:
area_order = g_df.sort_values('세대당 인구',ascending=False)['행정기관']

# subplots() 함수를 사용하여 axes 객체를 생성하기
figure, axes1 = plt.subplots(nrows=1,ncols=1)
figure.set_size_inches(18,12)

# seaborn의 barplot() 함수 호출하기 - 행정기관과 세대당 인구
sns.barplot(data=g_df, x="행정기관", y="세대당 인구", ax=axes1, hue="행정기관", order=area_order)

axes1.set_title(f'지역별 세대당 인구')
axes1.set_xticklabels(axes1.get_xticklabels(), rotation=45, horizontalalignment='right', fontsize=12)

plt.show()

##### 3. 남녀 비율 분석

In [93]:
p_data[['행정기관', '남여 비율']].sort_values(by='남여 비율', ascending=False).reset_index(drop=True)

       행정기관  남여 비율
0     울산광역시   1.06
1      충청남도   1.05
2      충청북도   1.04
3      경상남도   1.02
4      경상북도   1.02
5      전라남도   1.02
6       경기도   1.01
7   강원특별자치도   1.01
8   제주특별자치도   1.00
9     인천광역시   1.00
10  세종특별자치시   0.99
11    대전광역시   0.99
12  전북특별자치도   0.99
13    광주광역시   0.97
14    대구광역시   0.96
15    부산광역시   0.95
16    서울특별시   0.93

##### 3-1. 남녀 비율 분석 plot

In [ ]:
percent_order = g_df.sort_values('남여 비율',ascending=False)['행정기관']

# subplots() 함수를 사용하여 axes 객체를 생성하기
figure, axes1 = plt.subplots(nrows=1,ncols=1)
figure.set_size_inches(18,12)

# seaborn의 barplot() 함수 호출하기 - 행정기관과 남여 비율
sns.barplot(data=g_df, x="행정기관", y="남여 비율", ax=axes1, hue="행정기관", order=percent_order)

# pyplot의 axhline() 함수를 사용하여 기준점 생성하기 
axes1.axhline(1.0, color='red', linestyle='--', label='남녀 1:1 비율')
axes1.legend(loc='upper right', fontsize=12)

axes1.set_title(f'지역별 남녀 비율')
axes1.set_xticklabels(axes1.get_xticklabels(), rotation=45, horizontalalignment='right', fontsize=12)

plt.show()

##### 4. 남자초과 / 여자초과 분석

In [95]:
import numpy as np

conditions = [p_data['남여 비율'] > 1, p_data['남여 비율'] < 1, p_data['남여 비율'] == 1]
choices = ['남초', '여초', '동일']

p_data['남초여초'] = np.select(conditions, choices)

p_data[['행정기관', '남여 비율', '남초여초']]

       행정기관  남여 비율 남초여초
1     서울특별시   0.93   여초
2     부산광역시   0.95   여초
3     대구광역시   0.96   여초
4     인천광역시   1.00   동일
5     광주광역시   0.97   여초
6     대전광역시   0.99   여초
7     울산광역시   1.06   남초
8   세종특별자치시   0.99   여초
9       경기도   1.01   남초
10  강원특별자치도   1.01   남초
11     충청북도   1.04   남초
12     충청남도   1.05   남초
13  전북특별자치도   0.99   여초
14     전라남도   1.02   남초
15     경상북도   1.02   남초
16     경상남도   1.02   남초
17  제주특별자치도   1.00   동일

##### 5. 세대당 인구 평균보다 높은 지역

In [96]:
p_data.loc[p_data['세대당 인구'] >= p_data['세대당 인구'].mean(), ['행정기관', '세대당 인구']]\
           .sort_values('세대당 인구', ascending=False).reset_index(drop=True)

      행정기관  세대당 인구
0  세종특별자치시    2.39
1      경기도    2.26
2    울산광역시    2.22
3    인천광역시    2.20
4    대구광역시    2.14
5    광주광역시    2.14
6  제주특별자치도    2.13

##### 5-1. 남초 vs 여초 개수 plot (seaborn의 countplot) | 지역별 세대수 plot (seaborn의 barplot)

In [ ]:
# subplots() 함수를 사용하여 axes 객체를 생성하기
figure,(axes1,axes2) = plt.subplots(nrows=2,ncols=1)
figure.set_size_inches(18,12)

count_plot = sns.countplot(x='남초여초', data=p_data, order=['여초','동일','남초'], ax=axes1, hue='남초여초')
count_plot.set_title(f'남초 vs 여초 지역 개수')

pop_plot = sns.barplot(x='행정기관', y='세대수', data=g_df.sort_values(by='세대수',ascending=False), ax=axes2, hue='행정기관')
pop_plot.set_title(f'지역별 세대수')

plt.show()